apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-grpc-server
  labels:
    app: go-grpc-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-grpc-server
  template:
    metadata:
      labels:
        app: go-grpc-server
    spec:
      containers:
        - name: go-grpc-server
          image: larolman/go-grpc-server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9090
          envFrom:
            - secretRef:
                name: server-secret
---
apiVersion: v1
kind: Service
metadata:
  name: go-grpc-server
spec:
  selector:
    app: go-grpc-server
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: go-grpc-server-headless
spec:
  clusterIP: None
  selector:
    app: go-grpc-server
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090