apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  clusterIP: None
  ports:
    - protocol: TCP
      port: 39092
      targetPort: 39092
  selector:
    name:  kafka
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: kafka-service
subsets:
  - addresses:
      - ip: 192.168.0.2
    ports:
      - port: 39092
---
apiVersion: v1
kind: Service
metadata:
  name: schema-registry-service
spec:
  clusterIP: None
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  selector:
    name:  schema
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: schema-registry-service
subsets:
  - addresses:
      - ip: 192.168.0.2
    ports:
      - port: 8081